/*
 * OR Planner API
 *
 * Operating Room Planner API
 *
 * API version: 1.0.0
 * Contact: filip.chromek@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package or_planner

import (
	"github.com/gin-gonic/gin"
)

type ScheduledOperationsAPI interface {


    // CreateOperation Post /api/rooms/:roomId/operations
     CreateOperation(c *gin.Context)

    // DeleteOperation Delete /api/rooms/:roomId/operations/:opId
     DeleteOperation(c *gin.Context)

    // GetOperation Get /api/rooms/:roomId/operations/:opId
     GetOperation(c *gin.Context)

    // GetRoomOperations Get /api/rooms/:roomId/operations
     GetRoomOperations(c *gin.Context)

    // UpdateOperation Put /api/rooms/:roomId/operations/:opId
     UpdateOperation(c *gin.Context)

}