/*
 * OR Planner API
 *
 * Operating Room Planner API
 *
 * API version: 1.0.0
 * Contact: filip.chromek@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package or_planner

import (
	"github.com/gin-gonic/gin"
)

type MedicalStaffAPI interface {


    // CreateStaff Post /api/staff
     CreateStaff(c *gin.Context)

    // GetStaff Get /api/staff
     GetStaff(c *gin.Context)

    // GetStaffMember Get /api/staff/:staffId
     GetStaffMember(c *gin.Context)

    // UpdateStaffMember Put /api/staff/:staffId
     UpdateStaffMember(c *gin.Context)

}