/*
 * OR Planner API
 *
 * Operating Room Planner API
 *
 * API version: 1.0.0
 * Contact: filip.chromek@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package or_planner

import (
	"github.com/gin-gonic/gin"
)

type OperatingRoomsAPI interface {


    // CreateRoom Post /api/rooms
    // Create new operating room 
     CreateRoom(c *gin.Context)

    // GetRoom Get /api/rooms/:roomId
     GetRoom(c *gin.Context)

    // GetRooms Get /api/rooms
    // List all operating rooms 
     GetRooms(c *gin.Context)

    // UpdateRoom Put /api/rooms/:roomId
     UpdateRoom(c *gin.Context)

}