/*
 * OR Planner API
 *
 * Operating Room Planner API
 *
 * API version: 1.0.0
 * Contact: filip.chromek@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package or_planner

import (
	"github.com/gin-gonic/gin"
)

type PatientsAPI interface {


    // CreatePatient Post /api/patients
     CreatePatient(c *gin.Context)

    // GetPatient Get /api/patients/:patientId
     GetPatient(c *gin.Context)

    // GetPatients Get /api/patients
     GetPatients(c *gin.Context)

    // UpdatePatient Put /api/patients/:patientId
     UpdatePatient(c *gin.Context)

}