/*
 * OR Planner API
 *
 * Operating Room Planner API
 *
 * API version: 1.0.0
 * Contact: filip.chromek@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package or_planner

import (
	"time"
)

type MedicalStaffAvailabilityInner struct {

	From time.Time `json:"from"`

	To time.Time `json:"to"`
}
