/*
 * OR Planner API
 *
 * Operating Room Planner API
 *
 * API version: 1.0.0
 * Contact: filip.chromek@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package or_planner

type Patient struct {

	Id string `json:"id"`

	FirstName string `json:"firstName"`

	LastName string `json:"lastName"`

	// Slovak birth number, slash optional
	BirthNumber string `json:"birthNumber"`

	Contact string `json:"contact,omitempty"`

	// VšZP, Dôvera, Union
	Insurance string `json:"insurance,omitempty"`

	Archived bool `json:"archived,omitempty"`
}
