/*
 * OR Planner API
 *
 * Operating Room Planner API
 *
 * API version: 1.0.0
 * Contact: filip.chromek@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package or_planner

type OperatingRoom struct {

	Id string `json:"id"`

	Number string `json:"number"`

	Name string `json:"name"`

	// general, cardiac, orthopedic, etc.
	Type string `json:"type,omitempty"`

	Capacity int32 `json:"capacity,omitempty"`

	Equipment []string `json:"equipment,omitempty"`

	Status string `json:"status"`

	ScheduledOperations []ScheduledOperation `json:"scheduledOperations,omitempty"`

	PredefinedProcedures []ProcedureType `json:"predefinedProcedures,omitempty"`

	Archived bool `json:"archived,omitempty"`
}
