/*
 * OR Planner API
 *
 * Operating Room Planner API
 *
 * API version: 1.0.0
 * Contact: filip.chromek@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package or_planner

import (
	"time"
)

type ScheduledOperation struct {

	Id string `json:"id"`

	PatientId string `json:"patientId"`

	StaffIds []string `json:"staffIds,omitempty"`

	ProcedureType string `json:"procedureType"`

	Priority int32 `json:"priority,omitempty"`

	ScheduledStart time.Time `json:"scheduledStart"`

	DurationMinutes int32 `json:"durationMinutes"`

	Status string `json:"status,omitempty"`

	Notes string `json:"notes,omitempty"`
}
