/*
 * OR Planner API
 *
 * Operating Room Planner API
 *
 * API version: 1.0.0
 * Contact: filip.chromek@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package or_planner

type MedicalStaff struct {

	Id string `json:"id"`

	FirstName string `json:"firstName"`

	LastName string `json:"lastName"`

	Role string `json:"role"`

	Specialization string `json:"specialization,omitempty"`

	Availability []MedicalStaffAvailabilityInner `json:"availability,omitempty"`

	Archived bool `json:"archived,omitempty"`
}
