/*
 * OR Planner API
 *
 * Operating Room Planner API
 *
 * API version: 1.0.0
 * Contact: filip.chromek@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package or_planner

type ProcedureType struct {

	Code string `json:"code"`

	Name string `json:"name"`

	TypicalDurationMinutes int32 `json:"typicalDurationMinutes,omitempty"`
}
