/*
 * OR Planner API
 *
 * Operating Room Planner API
 *
 * API version: 1.0.0
 * Contact: filip.chromek@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package or_planner

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name		string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method		string
	// Pattern is the pattern of the URI.
	Pattern	 	string
	// HandlerFunc is the handler function of this route.
	HandlerFunc	gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the MedicalStaffAPI part of the API
	MedicalStaffAPI MedicalStaffAPI
	// Routes for the OperatingRoomsAPI part of the API
	OperatingRoomsAPI OperatingRoomsAPI
	// Routes for the PatientsAPI part of the API
	PatientsAPI PatientsAPI
	// Routes for the ScheduledOperationsAPI part of the API
	ScheduledOperationsAPI ScheduledOperationsAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{ 
		{
			"CreateStaff",
			http.MethodPost,
			"/api/staff",
			handleFunctions.MedicalStaffAPI.CreateStaff,
		},
		{
			"GetStaff",
			http.MethodGet,
			"/api/staff",
			handleFunctions.MedicalStaffAPI.GetStaff,
		},
		{
			"GetStaffMember",
			http.MethodGet,
			"/api/staff/:staffId",
			handleFunctions.MedicalStaffAPI.GetStaffMember,
		},
		{
			"UpdateStaffMember",
			http.MethodPut,
			"/api/staff/:staffId",
			handleFunctions.MedicalStaffAPI.UpdateStaffMember,
		},
		{
			"CreateRoom",
			http.MethodPost,
			"/api/rooms",
			handleFunctions.OperatingRoomsAPI.CreateRoom,
		},
		{
			"GetRoom",
			http.MethodGet,
			"/api/rooms/:roomId",
			handleFunctions.OperatingRoomsAPI.GetRoom,
		},
		{
			"GetRooms",
			http.MethodGet,
			"/api/rooms",
			handleFunctions.OperatingRoomsAPI.GetRooms,
		},
		{
			"UpdateRoom",
			http.MethodPut,
			"/api/rooms/:roomId",
			handleFunctions.OperatingRoomsAPI.UpdateRoom,
		},
		{
			"CreatePatient",
			http.MethodPost,
			"/api/patients",
			handleFunctions.PatientsAPI.CreatePatient,
		},
		{
			"GetPatient",
			http.MethodGet,
			"/api/patients/:patientId",
			handleFunctions.PatientsAPI.GetPatient,
		},
		{
			"GetPatients",
			http.MethodGet,
			"/api/patients",
			handleFunctions.PatientsAPI.GetPatients,
		},
		{
			"UpdatePatient",
			http.MethodPut,
			"/api/patients/:patientId",
			handleFunctions.PatientsAPI.UpdatePatient,
		},
		{
			"CreateOperation",
			http.MethodPost,
			"/api/rooms/:roomId/operations",
			handleFunctions.ScheduledOperationsAPI.CreateOperation,
		},
		{
			"DeleteOperation",
			http.MethodDelete,
			"/api/rooms/:roomId/operations/:opId",
			handleFunctions.ScheduledOperationsAPI.DeleteOperation,
		},
		{
			"GetOperation",
			http.MethodGet,
			"/api/rooms/:roomId/operations/:opId",
			handleFunctions.ScheduledOperationsAPI.GetOperation,
		},
		{
			"GetRoomOperations",
			http.MethodGet,
			"/api/rooms/:roomId/operations",
			handleFunctions.ScheduledOperationsAPI.GetRoomOperations,
		},
		{
			"UpdateOperation",
			http.MethodPut,
			"/api/rooms/:roomId/operations/:opId",
			handleFunctions.ScheduledOperationsAPI.UpdateOperation,
		},
	}
}
